version: '3.1'

services:
  jupyter:
    image: jupyter/base-notebook:latest 
    restart: always
    container_name: jupyter
    command: /bin/bash -c "pip3 install pandas pymysql && bash start-notebook.sh"
    ports:
      - 8888:8888
    volumes:
      - ./data:/home/jovyan/work
      - /etc/localtime:/etc/localtime:ro
    environment:
        - NB_USER=docker_worker
        - NB_UID=0
        - NB_GID=0
        - CHOWN_HOME=yes
        - CHOWN_HOME_OPT=-R
        - JUPYTER_TOKEN=123456 
